IF OBJECT_ID('dbo.messages','U') IS NOT NULL DROP TABLE dbo.messages;
IF OBJECT_ID('dbo.chats','U')   IS NOT NULL DROP TABLE dbo.chats;
GO

CREATE TABLE dbo.chats (
  id BIGINT IDENTITY PRIMARY KEY,
  title NVARCHAR(255) NULL,
  created_at DATETIME2 DEFAULT SYSDATETIME(),
  updated_at DATETIME2 DEFAULT SYSDATETIME()
);

CREATE TABLE dbo.messages (
  id BIGINT IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.chats(id) ON DELETE CASCADE,
  role NVARCHAR(16) NOT NULL,
  content NVARCHAR(MAX) NOT NULL,
  created_at DATETIME2 DEFAULT SYSDATETIME()
);
